"""Shared helpers for the E2E suite.

Registration/login go through the real HTTP API (fast, and the UI-driven
auth flow is separately exercised in test_auth_flow.py) - but seeding a
*complete* curriculum for the player/assessment tests goes through a direct
Prisma script, not the AI pipeline, because waiting on real Gemini calls
inside a browser test would make the suite slow and flaky through no fault
of the app (see TODO.md Phase 0/2's notes on free-tier quota). This mirrors
the "arrange fast via a direct path, act/assert through the real UI"
pattern already used for manual verification throughout this project.
"""

from __future__ import annotations

import json
import subprocess
import time
import uuid
from pathlib import Path

import requests

API_URL = "http://localhost:5001/api"
BACKEND_DIR = Path(__file__).resolve().parent.parent.parent / "backend"

# The classroom seeded by backend/prisma/seed.ts - reused rather than
# creating a new classroom per test.
SEEDED_CLASSROOM_ID = "cmrxoyir50004ulzk2gshxhw5"
SEEDED_TEACHER_EMAIL = "teacher@neurolearn.com"
SEEDED_TEACHER_PASSWORD = "Teacher@1234"


def unique_email(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:10]}@example.test"


def api_register_student(email: str, password: str = "TestPass123") -> dict:
    response = requests.post(
        f"{API_URL}/auth/register",
        json={"name": "E2E Test Student", "email": email, "password": password},
        timeout=15,
    )
    response.raise_for_status()
    return response.json()


def api_login(email: str, password: str) -> dict:
    response = requests.post(f"{API_URL}/auth/login", json={"email": email, "password": password}, timeout=15)
    response.raise_for_status()
    return response.json()


def _run_node_script(script: str) -> str:
    """Runs a short Node script against the backend's Prisma client - the
    same pattern used for manual DB seeding/cleanup throughout this project.
    """
    result = subprocess.run(
        ["node", "-e", script],
        cwd=str(BACKEND_DIR),
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Node seed script failed:\n{result.stderr}")
    return result.stdout.strip()


def seed_enrolled_student() -> dict:
    """Registers a fresh student via the real API, then enrolls them in the
    seeded classroom directly (enrollment normally goes through a join-
    request/approval flow that isn't the point of these tests).
    """
    email = unique_email("e2e-student")
    auth = api_register_student(email)
    student_id = auth["user"]["id"]

    _run_node_script(
        f"""
        const {{ PrismaClient }} = require('@prisma/client');
        const prisma = new PrismaClient();
        (async () => {{
          await prisma.enrolment.create({{ data: {{ classroomId: '{SEEDED_CLASSROOM_ID}', studentId: '{student_id}' }} }});
          await prisma.$disconnect();
        }})();
        """
    )
    return {"email": email, "password": "TestPass123", "token": auth["token"], "id": student_id}


def seed_curriculum(with_final_assessment: bool = True) -> dict:
    """Creates a disposable subject/unit with a small, complete
    TutorialCurriculum (2 lessons, one with a knowledge check, optionally a
    final assessment question) - deterministic content for UI tests, not
    generated by the AI pipeline.
    """
    suffix = uuid.uuid4().hex[:8]
    final_assessment_block = (
        """
        finalAssessmentQuestions: {
          create: [{ order: 0, question: 'What gas do plants release?', options: ['Oxygen', 'Nitrogen', 'Helium'], correct: 'Oxygen' }]
        }
        """
        if with_final_assessment
        else ""
    )
    script = f"""
    const {{ PrismaClient }} = require('@prisma/client');
    const prisma = new PrismaClient();
    (async () => {{
      const subject = await prisma.subject.create({{ data: {{ classroomId: '{SEEDED_CLASSROOM_ID}', name: 'E2E Subject {suffix}' }} }});
      const unit = await prisma.unit.create({{ data: {{ subjectId: subject.id, title: 'E2E Unit {suffix}', ragUnitId: Math.floor(Math.random() * 900000) + 100000, indexStatus: 'READY' }} }});
      const curriculum = await prisma.tutorialCurriculum.create({{
        data: {{
          unitId: unit.id,
          title: 'Photosynthesis Basics {suffix}',
          sourceChunks: 2,
          lessons: {{
            create: [
              {{
                order: 0,
                title: 'What is Photosynthesis?',
                explanation: 'Plants use sunlight to make food from carbon dioxide and water.',
                example: 'A leaf in sunlight produces oxygen.',
                knowledgeCheck: {{ create: {{ question: 'What do plants use to make food?', options: ['Sunlight', 'Moonlight', 'Fire'], correct: 'Sunlight' }} }}
              }},
              {{
                order: 1,
                title: 'Why Oxygen Matters',
                explanation: 'Plants release oxygen as a byproduct, which animals need to breathe.',
                example: 'Humans breathe oxygen released by trees.'
              }}
            ]
          }},
          {final_assessment_block}
        }},
        include: {{ lessons: true }}
      }});
      console.log(JSON.stringify({{ unitId: unit.id, subjectId: subject.id, curriculumId: curriculum.id }}));
      await prisma.$disconnect();
    }})();
    """
    output = _run_node_script(script)
    return json.loads(output)


def seed_bare_subject_and_unit() -> dict:
    """A fresh subject+unit with nothing indexed yet - for the upload-flow
    test, which drives the real PDF-upload UI itself rather than pre-seeding
    a curriculum.
    """
    suffix = uuid.uuid4().hex[:8]
    script = f"""
    const {{ PrismaClient }} = require('@prisma/client');
    const prisma = new PrismaClient();
    (async () => {{
      const subject = await prisma.subject.create({{ data: {{ classroomId: '{SEEDED_CLASSROOM_ID}', name: 'E2E Upload Subject {suffix}' }} }});
      const unit = await prisma.unit.create({{ data: {{ subjectId: subject.id, title: 'E2E Upload Unit {suffix}' }} }});
      console.log(JSON.stringify({{ unitId: unit.id, subjectId: subject.id, unitTitle: unit.title }}));
      await prisma.$disconnect();
    }})();
    """
    return json.loads(_run_node_script(script))


def cleanup_subject(subject_id: str) -> None:
    _run_node_script(
        f"""
        const {{ PrismaClient }} = require('@prisma/client');
        const prisma = new PrismaClient();
        (async () => {{
          await prisma.subject.delete({{ where: {{ id: '{subject_id}' }} }}).catch(() => {{}});
          await prisma.$disconnect();
        }})();
        """
    )


def cleanup_user(user_id: str) -> None:
    _run_node_script(
        f"""
        const {{ PrismaClient }} = require('@prisma/client');
        const prisma = new PrismaClient();
        (async () => {{
          await prisma.user.delete({{ where: {{ id: '{user_id}' }} }}).catch(() => {{}});
          await prisma.$disconnect();
        }})();
        """
    )


def set_local_storage_token(driver, base_url: str, token: str) -> None:
    """Logs the browser in without driving the login form - used by tests
    whose focus is a downstream page, not the login flow itself (that flow
    has its own dedicated test in test_auth_flow.py).
    """
    driver.get(base_url)
    driver.execute_script("window.localStorage.setItem('token', arguments[0]);", token)


def wait_until(predicate, timeout: float = 20.0, interval: float = 0.5, message: str = "condition not met"):
    deadline = time.time() + timeout
    last_exc = None
    while time.time() < deadline:
        try:
            if predicate():
                return True
        except Exception as exc:  # noqa: BLE001 - re-raised as a clear timeout below
            last_exc = exc
        time.sleep(interval)
    raise TimeoutError(f"{message} (waited {timeout}s)" + (f" - last error: {last_exc}" if last_exc else ""))
